version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: back/Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env
    restart: always
  tests:
    build:
      context: .
      dockerfile: back/Dockerfile
    command: >
      bash -c "
        echo 'Waiting for Postgres...' &&
        sleep 5 &&
        python -m pytest tests/unit/ &&
        python -m pytest tests/integration/"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: "no"

  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
    env_file:
      - .env
    restart: always

volumes:
  postgres_data:
