name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build and run tests
      run: |
        docker-compose build tests
        docker-compose run --rm tests

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Prepare server directory
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          rm -rf ~/app
          mkdir -p ~/app
        "

    - name: Copy project files
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='.gitignore' \
          ./ \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/app/

    - name: Set correct permissions
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          chmod 600 ~/app/.env
          chmod -R u+r ~/app
        "

    - name: Rebuild and restart services
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd ~/app
          docker-compose down
          docker-compose up --build -d
        "
